server:
  error:
    include-stacktrace: never
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/anime?serverTimeZone=America/Sao_Paulo&createDatabaseIfNotExist=True&useSSL=false
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: springboot2-essentials
#    properties:
#      hibernate:
#        format_sql: false
#    show-sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus
  endpoint:
    health:
      show-details: when_authorized

info:
  app: Spring Boot 2 Essentials
  website: https://andrelucasrs.github.io/
  github: https://github.com/AndreLucasrs/springboot2-essentials
  api: http://localhost:8080/swagger-ui.html